package d.pojos;
// Generated 22-feb-2016 15:36:18 by Hibernate Tools 4.3.1



/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private boolean selected;

    /*Se agrega isSelected y setSelected ya que se generea una variable boolean*/
    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }
     
     
    public Departamento() {
    }

    public Departamento(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


