package d.pojos;
// Generated 22-feb-2016 15:36:18 by Hibernate Tools 4.3.1



/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private long ci;
     private String nombre;
     private String direccion;
     private char genero;
     private int departamento;
     private String foto;

    public Empleado() {
    }

    public Empleado(long ci, String nombre, String direccion, char genero, int departamento, String foto) {
       this.ci = ci;
       this.nombre = nombre;
       this.direccion = direccion;
       this.genero = genero;
       this.departamento = departamento;
       this.foto = foto;
    }
   
    public long getCi() {
        return this.ci;
    }
    
    public void setCi(long ci) {
        this.ci = ci;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public char getGenero() {
        return this.genero;
    }
    
    public void setGenero(char genero) {
        this.genero = genero;
    }
    public int getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(int departamento) {
        this.departamento = departamento;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


