package d.pojos;
// Generated 22-feb-2016 15:36:18 by Hibernate Tools 4.3.1



/**
 * Encuesta generated by hbm2java
 */
public class Encuesta  implements java.io.Serializable {


     private Integer id;
     private int voto;

    public Encuesta() {
    }

    public Encuesta(int voto) {
       this.voto = voto;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getVoto() {
        return this.voto;
    }
    
    public void setVoto(int voto) {
        this.voto = voto;
    }




}


