package d.pojos;
// Generated 22-feb-2016 15:36:18 by Hibernate Tools 4.3.1



/**
 * Prueba generated by hbm2java
 */
public class Prueba  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String apellido;
     private String cedula;

    public Prueba() {
    }

    public Prueba(String nombre, String apellido, String cedula) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.cedula = cedula;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getCedula() {
        return this.cedula;
    }
    
    public void setCedula(String cedula) {
        this.cedula = cedula;
    }




}


