package d.pojos;
// Generated 22-feb-2016 15:36:18 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Temas generated by hbm2java
 */
public class Temas  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String tema;
     private Date fecha;

    public Temas() {
    }

    public Temas(String nombre, String tema, Date fecha) {
       this.nombre = nombre;
       this.tema = tema;
       this.fecha = fecha;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


